In [6]:
#stop integer is exclusive
list_two = list(range(1,4))
list_three = list(range(1,4))
print(list_two)
print(list_three)

#this means empty list 
list_sum = []

#3 corresponds to the length of both lists
for index in range(3):
    #raising each value to the 2nd power
    list_two[index] = list_two[index] ** 2
    #raising each value to the 3rd power
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])

    
print(list_two)
print(list_three)
print(list_sum)

[1, 2, 3]
[1, 2, 3]
[1, 4, 9]
[1, 8, 27]
[2, 12, 36]


In [2]:
import numpy as np
#arrange is simialar to the range in python. Prints array instead of list
array_two = np.arange(1,4) ** 2
#arrays have no commas. We can directly do math on array, but not on lists
print(array_two)
array_three = np.arange(1,4) ** 3
print(array_three)
print(array_two + array_three)

#we cannot add lists directly together, but can with arrays
#numpy has a lot of mathetmatical functions that we can use on arrays

[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [26]:
#np.power raise all numbers to a corresponding power. 
#np.array Converts a list to an array. 4 is the corresponding power
print(np.power(np.array([1, 2, 3]), 4))

#Could also to do 
#print(np.array([1, 2, 3]) ** 4)

[ 1 16 81]


In [28]:
#gives you negative values of everything
print(np.negative(np.array([1, 2, 3])))

[-1 -2 -3]


In [29]:
#gives you exponential. e^1, e^2, e^3
sample_array = np.array([1, 2, 3])
print(np.exp(sample_array))

[ 2.71828183  7.3890561  20.08553692]


In [30]:
#take the log of everything
print(np.log(sample_array))

[0.         0.69314718 1.09861229]


In [31]:
#take the sin of all values
print(np.sin(sample_array))

[0.84147098 0.90929743 0.14112001]


In [39]:
#numpy has these mathematical functions that are 
#available to us that are much simpler than python counterpart

import numpy as np
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x, y, z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [40]:
#1D array of numbers between 1 to 10, with 50 numbers inbetween evenly spaced
w = np.linspace(1, 10, 50)
print(w)

#not the same as space integer

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [48]:
#grabs every 3rd element. Doesn't include 30! exclusive. final entry gives you step
b = np.arange(1, 30, 3)
print(b)

#grabs 3 numbers between 1 to 30 evenly spaced. Final entry true/false lets the number go to 30 or not
a = np.linspace(1, 30, 3, True)
print(a)

[ 1  4  7 10 13 16 19 22 25 28]
[ 1.  15.5 30. ]


In [51]:
import numpy as np
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z])
print(multi_array)
print(multi_array.shape)
#rows and columns are indexed starting from 0
multi_array[1,2]

#numpy arras are homogeneous, so elements are described as data type

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


5

In [53]:
print(multi_array.dtype)
#all the elements are 64 bit integers. 
#can also change to np.unit8 or int16, etc. 

int64


In [61]:
#How to do 1D slicing of arrays
#slicing has a start, stop and step (space in between the values)
import numpy as np
x = np.arange(1, 10)
print(x)

#now want to grab everything from 3 to 7 (which is index starting 0 to 6)
print(x[2:7])

#this prints every 2nd value
print(x[2:7:2])


[1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[3 5 7]


In [71]:
#Reshape multi_dimensional arrays
import numpy as np
#9 elements ranging from 0 to 8
x = np.arange(9) 
#print(x)

#now we're going to reshape to have 3 rows and 3 columns
x = np.arange(9).reshape(3, 3)
#print(x)
#can also do x = np.arange(9).reshape(3, -1). the -1 is the unknown based on 3 rows

#this array has 18 elements, to have 2 blocks of data with 3x3 arrays
x = np.arange(18).reshape(2,3,3)
#print(x)

#3 blocks of data, with 3 rows and 2 columns. Reshape must be compatible with dimensions of data
x = np.arange(18).reshape(3,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [87]:
#multidimensional slicing
import numpy as np
x = np.arange(18).reshape(3, 2, 3)
print(x)

#building with 3 floors. Starts with 0 index. Selecting 10
print(x[1,1,1])

#If we want to slice 6 to 11, 2nd block of data with index of 1
#both present in the 1st and 2nd row so we go from 0:2
#all present in the 1st to 3rd column, so we go from 0:3 (exclusive to 2)
#print(x[1, 0:2, 0:3])

#we can also omit the range, so it is inferred to access from 0
#print(x[1, :2, :3])

#but can also omit the stop integer to get the entire row and column too
#print(x[1, :, :])

#another way is to just use ellipses as a shortcut
print(x[1, ...])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
10
[[ 6  7  8]
 [ 9 10 11]]


In [89]:
#to just get the first valaue 0 row and 0 column, of each box
print(x[:, 0, 0])

[ 0  6 12]


In [90]:
#can also select the 2nd element of each slice by setting a step size of 2
print(x[1, :2, :3 :2])

[[ 6  8]
 [ 9 11]]


In [92]:
#This evaluates the elements in x, if they're greater than 5
comparison_operation = x > 5
print(comparison_operation)

#Can then just get the values of x that are greater than 5
print(x[comparison_operation])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [93]:
#Can also do this directly
print(x[x>5])

[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [97]:
#grab the maximum number with
print(x.max())

#grab the minimum number with
print(x.min())

17
0


In [112]:
#manipulating array shapes
#ravel condenses a multidimensional array into a 1D array
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)

ravelled_array = x.ravel()
print(ravelled_array)

#can also do the same with the 'flattened', but the difference can't be seen with print statement
#flatten only returns a copy and allocates new memory while ravel returns a view 
flattened_array = x.flatten()
print(flattened_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [110]:
#if modify ravel, it would also modify the original array
ravelled_array[2] = 1000000
print(ravelled_array)
print(x)
#the change is reflected in both

[      0       1 1000000       3       4       5       6       7       8]
[[      0       1 1000000]
 [      3       4       5]
 [      6       7       8]]


In [115]:
#but since flatten stores a copy, changing a value will not have an effect on the original array
flattened_array = x.flatten()
flattened_array[2] = 1000000
print(flattened_array)
print(x)

#flatten allocates memory and ravel may be good, but need to be mindful ravel changes original too

[      0       1 1000000       3       4       5       6       7       8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [119]:
y = np.arange(9)
#don't need to use .reshape, can set shape like so
y.shape = [3,3]
print(y)

#can also flip along diagonal, or get it's transpose. need to put argument of none
print(y.transpose())
#can also use y.T, with no arguments
print(y.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [121]:
#if want to resize the data to a bigger one, can resize and the data will repeat to fill it up
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [130]:
print(np.zeros((3), dtype=int))

#can also arrange the data in a different shape
print(np.zeros((3,2), dtype=int))

[0 0 0]
[[0 0]
 [0 0]
 [0 0]]


In [131]:
#instead of zeros you can get ones instead
print(np.ones((3,2), dtype=int))

[[1 1]
 [1 1]
 [1 1]]


In [134]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [136]:
#prints random values between 0 and 1
print(np.random.rand(4,4))

[[0.60038393 0.57031672 0.9336135  0.59186764]
 [0.66662002 0.16222037 0.13477845 0.08834588]
 [0.51047132 0.67512818 0.73052032 0.59074635]
 [0.6806813  0.55804561 0.76726623 0.2298074 ]]


In [150]:
#multiplying matrices together
import numpy as np
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2,3)
print(mat_a)

#can also write np.array too
mat_aa = np.array([0, 3, 5, 5, 5, 2]).reshape(2,3)
print(mat_aa)

[[0 3 5]
 [5 5 2]]
[[0 3 5]
 [5 5 2]]


In [144]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3,2)
print(mat_b)

[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [151]:
print(mat_a * mat_b)

#can also write this
product = np.matmul(mat_a, mat_b)
print(product)

#can also do this
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]


In [18]:
#Stacking
import numpy as np

#making an array with 4 elements 0 to 3 (index starts at zero)
x = np.arange(4).reshape(2,2)
print(x)

#making a new array with 4 elements, numbers 4 to 7
y = np.arange(4, 8).reshape(2,2)
print(y)

#to stack the two matrices horizontally. to do this both need to have same number of rows
z = np.hstack((x, y))
print(z)
#looking at the shape of z, the number of columns increases 2x4
print(z.shape)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [19]:
#when vertically stacking, the arrays must have the same number of columns instead
yy = np.arange(8).reshape(4,2)
print(yy)

#increases the number of rows instead of columns
zz = np.vstack((x, yy))
print(zz)
print(zz.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
(6, 2)


In [20]:
#similar to stacking is concatenate. with the axis = 0, that's the rows. so similar to vstack
w = np.concatenate((x,y), axis = 0)
print(w)

#axis 1 is for the horizontal stacking, so make sure the number of rows match
v = np.concatenate((x,y), axis = 1)
print(v)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [21]:
#can also horizontally stack both which is the same as concatenating on the aaxis 1
z = np.hstack((x,y))
print(z)
#compare to arrays
print(z == v)


[[0 1 4 5]
 [2 3 6 7]]
[[ True  True  True  True]
 [ True  True  True  True]]


In [22]:
#depth stacking is stacking on the 3rd axis. Need to have equiv rows and columsn
y = x * 2
#both of these arrays are 2D. depth stack stacks on 3D, so it will reshape both arrays and add another 
#dimension with size 1
depth_stack = np.dstack((x,y))
print(depth_stack)
#two floors, two rows, two columns
print(depth_stack.shape)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)


In [25]:
#column stacking stacks arrays on the 2nd axis. equiv. to hstacking
print(np.column_stack((x,y)))
#two equal bars is comparison
print(np.column_stack((x,y)) == np.hstack((x,y)))

#but these two functions not equiv when using 1D arrays 
s = np.arange(4)
t = s * 2
#still stacks by columns to make a 2D array
print(np.column_stack((s,t)))
print(np.hstack((s,t)))

[[0 1 0 2]
 [2 3 4 6]]
[[ True  True  True  True]
 [ True  True  True  True]]
[[0 0]
 [1 2]
 [2 4]
 [3 6]]
[0 1 2 3 0 2 4 6]


In [27]:
#row stack is similar to vertical stacking
print(np.row_stack((x,y)) == np.vstack((x,y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
